language: node_js
node_js:
- 4.0.0
before_script:
- npm install -g gulp
script:
- gulp travis
sudo: false
deploy:
  provider: heroku
  app: logbotcmd
  skip_cleanup: true
  api_key:
    secure: tmB8d5/Xbjzj39Sur7VEFmulrEH+xhziYSXR/BT6btx/lnIW3SHdOfNMNeKchlS+KbMnw5YX0TlJDMTsWnmTMWqi9RfDbualbreWvP3AQZfkpz0sPVvQuhTuUiDudRohQs5zZlhyW8MJk40tGe94hGkcoL13w7lWlwLZQFdXjXhyqUn1LbFTNfQJcDtnFIWp3Jtmgvc/wNTp91XDyThWSqJ+bXF/WZnw9L8YjlbwGhQvq2fv3EJJYys53aEgudKtxhoKp5JX7X5bEa4s8kSCDNT6V7zMu2F8H4noAiYu4lNKEiBhkX4yhVrjxtZBbl1D4SCaci3wILY1rS18jBKnl6sra1TrZ4BNOneO6gKynyUPbYEJfZo4vOaz1aH1crEvMgZcYBl34VUjwUiYWqrpcYcImVp3oGkLQlh+yb1QuwknPTO9+d5WSqVrkxeiD+dzgQfSaN5ewOoTNFIdXDfa73tZByrIOGwiqsabDHwrIEvTJCSgA2fYE+QpdtadLopb6NwMiPdym9XRm5hZc8NH/MYAyd6G8DKN/1qdQcpXQkaFca/Tflnnc8U2vLhObFfoAz5HhmjeuGpQAldNgYucC8HIbC0q/vBRWZnG80oBvZVgz0LpCWtUerMa0lL2bk2SB3BwKPMrScoB5mvzI5PRAJS4lpdJCdHY1Ts884Y0kTo=
